#include <vector>
#include <map>
#include <string>
#include <queue>
#include <sstream>
#include <stack>
#include <set>
#include <bitset>

using namespace std;

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/

char findTheDifference(string s, string t) {
	vector<int>countA(256, 0);
	vector<int>countB(256, 0);

	for (auto c : s) {
		countA[c]++;
	}

	for (auto c : t) {
		countB[c]++;
	}

	for (int i = 0; i < 256; i++) {
		if (countA[i] != countB[i]) {
			return i;
		}
	}

	return 'a';

}