#include<vector>
#include<map>
#include<string>
#include<queue>
#include<sstream>

using namespace std;


/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/    
    
/**
 * @param s: a string
 * @param t: a string
 * @return: the letter that was added in t
 */
char findTheDifference(string &s, string &t) {
    // Write your code here
    
    int sum{0};
    //sum of target string
    for(int i = 0;i<t.size();i++){
        sum += (t[i]-'a');
    }
    //sum of original string
    for(int i = 0;i<s.size();i++){
        sum -=(s[i]-'a');
    }
    
    return 'a'+sum;
}